name: tekartik_sw_build
description: Service worker build utils
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  tekartik_sw_utils:
    git:
      url: git@github.com/tekartik/app_web_utils.dart
      ref: dart3a
      path: packages/sw_utils
    version: '>=0.1.0'
  crypto:
  process_run:
  path:
dev_dependencies:
  test: ^1.14.4
  tekartik_app_web_build:
    path: ../app_build
  build_runner:
  build_web_compilers:

dependency_overrides:
  tekartik_sw_utils:
    path: ../sw_utils
