name: tekartik_sw_utils
description: Service worker utils
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  service_worker:
    git:
      url: git://github.com/tekartikdev/service_worker
      ref: null_safety
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: null_safety
    version: '>=0.6.13'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
