name: tekartik_sw_utils
description: Service worker utils
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  service_worker: '>=0.3.0-0'
  #  git:
  #    url: https://github.com/tekartikdev/service_worker
  #    ref: dart2_3
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart2_3
    version: '>=0.6.13'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4