name: tekartik_sw_utils
description: Service worker utils
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  service_worker: '>=0.3.0-0'
  #  git:
  #    url: https://github.com/tekartikdev/service_worker
  #    ref: dart3a
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.6.13'

dev_dependencies:
  test: ">=1.24.0"
resolution: workspace
