name: tekartik_web_splash
description: Basic web splash support.
version: 0.4.0

environment:
  sdk: ^3.5.0

dependencies:
  web: '>=0.5.0'

dev_dependencies:
  lints: '>=3.0.0'
  test: '>=1.19.0'
  build_runner: '>=2.3.0'
  build_web_compilers: '>=4.0.9'
