name: tekartik_web_splash
description: Basic web splash support.
version: 0.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0