name: tekartik_web_splash
description: Basic web splash support.
version: 0.4.0

environment:
  sdk: ^3.9.0

dependencies:
  web: '>=0.5.0'

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
resolution: workspace
