name: tekartik_web_splash
description: Basic web splash support.
version: 0.3.0

environment:
  sdk: '>=2.18.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  lints:
  test: '>=1.19.0'
  build_runner: '>=2.3.0'
  build_web_compilers: '>=3.2.0'