name: tekartik_three_js
description: Three js experimental js bindings
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  cv: ">=1.1.1"
  web: '>=1.1.0'
  pub_semver: ">=2.1.4"
  tekartik_js_utils_interop:
    git:
      url: https://github.com/tekartik/js_utils.dart
      ref: dart3a
      path: js_utils_interop
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      ref: dart3a
      path: js_utils

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
resolution: workspace
