name: tekartik_app_web_build_menu
description: Build menu for web app (dart, not flutter)
version: 1.0.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path:
  args:
  dev_build: '>=0.16.5-6'
  process_run:
  tekartik_app_web_build:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      path: packages/app_build
      ref: dart3a
    version: '>=0.1.1'
  tekartik_firebase_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/firebase_build

dev_dependencies:
  # Needed direct dependencies
  build_runner:
  build_web_compilers:
  lints: '>=2.0.0'
  test: '>=1.16.0'

dependency_overrides:
  tekartik_app_web_build:
    path: ../app_build

executables:
  wbm: wbm
