name: tekartik_app_web_build_menu
description: Build menu for web app (dart, not flutter)
version: 1.0.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path:
  args:
  dev_test:
  process_run:
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu_io
  tekartik_test_menu:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu
  tekartik_app_web_build:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      path: packages/app_build
      ref: dart3a
    version: '>=0.1.1'

dev_dependencies:
  # Needed direct dependencies
  build_runner:
  build_web_compilers:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  tekartik_app_web_build:
    path: ../app_build

executables:
  wbm: wbm
