name: tekartik_app_web_build_menu
description: Build menu for web app (dart, not flutter)
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path:
  args:
  dev_test:
  process_run:
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart2_3
      path: test_menu_io
  tekartik_test_menu:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart2_3
      path: test_menu
  tekartik_app_web_build:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      path: app_build
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3

dev_dependencies:
  # Needed direct dependencies
  build_runner:
  build_web_compilers:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  tekartik_app_web_build:
    path: ../app_build

executables:
  wbm: wbm