name: tekartik_app_web_build_menu
description: Build menu for web app (dart, not flutter)
version: 1.0.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.8.0

dependencies:
  path: ">=1.9.0"
  args: ">=2.6.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  tekartik_app_web_build:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      path: packages/app_build
      ref: dart3a
    version: '>=0.1.1'
  tekartik_firebase_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/firebase_build
  tekartik_web_publish:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/web_publish

dev_dependencies:
  # Needed direct dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  lints: ">=5.0.0"
  test: ">=1.24.0"

dependency_overrides:

  # Tmp
  # tekartik_web_publish:
  #  path: ../../../app_build.dart/packages/web_publish
  # tekartik_firebase_build:
  #  path: ../../../app_build.dart/packages/firebase_build

executables:
  wbm: wbm
resolution: workspace
