name: app_web_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: ^3.12.0

dev_dependencies:
  test: ">=1.31.0"
  dev_build: ">=1.1.7+3"
  lints: ">=6.1.0"

dependency_overrides:
resolution: workspace
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
