name: tekartik_app_web_build
description: Web app build helper
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart3a
    version: '>=0.6.2'
  crypto:
  process_run:
  dev_build:
  fs_shim:
  path:
  tekartik_firebase_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/firebase_build
  tekartik_web_publish:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/web_publish
  tekartik_common_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/common_build
dev_dependencies:
  test: '>=1.14.4'
  tekartik_sw_build:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      ref: dart3a
      path: packages/sw_build
    version: '>=0.1.0'

dependency_overrides:
  tekartik_sw_build:
    path: ../sw_build
  tekartik_sw_utils:
    path: ../sw_utils
  # Tmp
  # tekartik_web_publish:
  #  path: ../../../app_build.dart/packages/web_publish
  # tekartik_firebase_build:
  #  path: ../../../app_build.dart/packages/firebase_build
