name: tekartik_app_web_build
description: Web app build helper
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart2_3
    version: '>=0.6.2'
  crypto:
  process_run:
  dev_test:
  fs_shim:
  path:

dev_dependencies:
  test: ^1.14.4
  tekartik_sw_build:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      ref: dart2_3
      path: packages/sw_build
    version: '>=0.1.0'

dependency_overrides:
  tekartik_sw_build:
    path: ../sw_build
  tekartik_sw_utils:
    path: ../sw_utils